### ISSUE TITLE
Hapi8: empty return

### ISSUE THREAD

**Issue by ShujaatTariq** [creativelive/hapi-ratelimit#15]
Newer version of Hapi seems to have broken this plugin, i cant make it work on 8.2,(using the sample code).

Any solutions ?

**Comment by joseph-norman** [comment]
+1 for this, having the same issue.

**Comment by cl-aaron** [comment]
Hey guys, I'll try to make an update soon. I recently merged in a submitted patch to bring this up to hapi 8. However, it did not pass the functional tests and so I haven't updated npm yet.

**Comment by joseph-norman** [comment]
Thanks @cl-aaron much appreciated!
